### ISSUE TITLE
Claim cylon on PyPi

### ISSUE THREAD

**Issue by dguibert** [iqbal-lab-org/cylon#21]
I've proposed a patch series for viridian_workflow and its dependencies to be packaged inside the SPACK package manager.
See https://github.com/spack/spack/pull/28534.

During the review process, It was suggested that you may have to claim the cylon package on pypi.
See https://github.com/spack/spack/pull/28534#discussion_r1368918148

**Comment by iqbal-lab** [comment]
Thanks! @martinghunt is on vacation til Thursday,  will respond then

**Comment by martinghunt** [comment]
Easier to rename this repo to a name that is available on pypi?

**Comment by iqbal-lab** [comment]
Ah..yes makes sense!

**Comment by bede** [comment]
You could also do the thing where your importable package is named one thing and your PyPI package is named another. Trying to figure out how to do this atm as it happens...On 26 Oct 2023, at 11:55, Zamin Iqbal ***@***.***> wrote:﻿
Ah..yes makes sense!

**Comment by dguibert** [comment]
Hi, any progress on this?
I was waiting... so if you don't plan any action soon lt me know.
As suggested on my PR on the SPACK repository, I'll exclude cyclon from my PR.

**Comment by iqbal-lab** [comment]
sorry for the delay! Thinking some more, we were a bit befuddled by this.
1. we do not think people should ever use cylon except within viridian-workflow, so maybe no need for you to include it on its own
2. viridian-workflow has dependencies on non-pip-installable things, so it doesnt make sense to pip install it either.
(that a correct summary @martinghunt ?)

**Comment by martinghunt** [comment]
Yes @iqbal-lab agreed.

**Comment by dguibert** [comment]
Indeed pip is not useable to install cyclon nor viridian-workflow. That why I've packaged them in SPACK to be installed and profiled on one x86 node versus one aarch64 node (Ampere one).

I can't spend much time on this as our task on the project are done. But I can help if you want your tool(s) to be available in the SPACK package manager so it could be deployed easily.

If `cyclon` is only use inside `viridian-workflow` why not developping it inside the same repository and have your python package registred on pypi under the name `viridian-workflow`?

Feel free to close this issue or comment if you want me to put the last effort for `viridian-workflow` and `cyclon` to available on SPACK, up to you.

**Comment by iqbal-lab** [comment]
thanks for your response! i'm fine for viridian not to be in SPACK.
in answer to your question -  we leave cylon out, in case we want to incorporate it in other tools we build (although I will ask @martinghunt if he wants to just absorb it in, it';s a good question)
Closing this for now, and we will think about your suggestion! Thanks
