### ISSUE TITLE
update README on output files

### ISSUE THREAD

**Issue by iqbal-lab** [iqbal-lab-org/cylon#6]
Leaves out VCF. currently says

**Output**
The important files are:

consensus.final_assembly.fa: this contains the consensus sequence.
amplicon_data.json: JSON file containing details of what happened when trying to make a consensus sequence of each amplicon.

**Comment by martinghunt** [comment]
The VCF is made by viridian workflow, not virdian

**Comment by iqbal-lab** [comment]
oh sorry
